# Generated by Django 4.1 on 2023-05-06 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rabotakg', '0002_alter_vacancy_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='company_name',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
