# Generated by Django 4.1 on 2023-05-11 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rabotakg', '0005_company_region_vacancycategory_topvacancy'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VacancyCategory',
            new_name='Category',
        ),
        migrations.RemoveField(
            model_name='topvacancy',
            name='company_name',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
