# Generated by Django 4.1.1 on 2023-05-12 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rabotakg', '0006_rename_vacancycategory_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='vacancy_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vacancy', to='rabotakg.category'),
        ),
    ]
