# Generated by Django 4.1.1 on 2023-05-12 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rabotakg', '0007_vacancy_vacancy_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vacancy', to='rabotakg.region'),
        ),
    ]
