# Generated by Django 4.1.1 on 2023-05-12 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rabotakg', '0008_vacancy_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
